name: zilli
description: zilli app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

#  launcher_icon.png
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  nb_utils: ^5.0.6
  google_fonts: ^4.0.3
  smooth_page_indicator: ^1.0.0+2
  feather_icons: ^1.2.0
  font_awesome_flutter: ^10.1.0
  bottom_bar: ^2.0.1
  material_design_icons_flutter: ^6.0.7096
  bootstrap_icons: ^1.8.1
  circular_countdown_timer: ^0.2.2
  in_app_review: ^2.0.4
  share_plus: ^6.3.1
  percent_indicator: ^4.0.1
  http: ^0.13.4
  flutter_riverpod: ^2.3.2
  google_mobile_ads: ^2.3.0
  startapp_sdk: ^0.4.0
  applovin_max: ^2.4.4
  flutter_fortune_wheel: ^1.2.0
  flutter_tapjoy: ^2.1.0
  flutter_user_agentx: ^1.2.4
  vungle: ^0.6.10
  facebook_audience_network: ^1.0.1
  unity_ads_plugin: ^0.3.6
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.2
  assets_audio_player: ^3.0.5
  date_time_format: ^2.0.1
  url_launcher: ^6.1.6
  lottie: ^2.0.0
  internet_connection_checker: ^1.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logoicon.png"

flutter:


  uses-material-design: true
  assets:
    - images/